version: '3.7'

services:
  traefik:
    container_name: traefik
    image: traefik:v2.3
    build: 
      context: Dockerfile
    labels:
      - traefik.enable=true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./traefik_dynamic.toml:/traefik_dynamic.toml
      - /var/:/var/acme.json
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge