version: '3.7'

services:
  traefik:
    image: traefik:v2.3
    build: 
      context: Dockerfile
    labels:
      - traefik.enable=true
    ports:
    - 80:80
    - 443:443
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./traefik.toml:/traefik.toml
    - ./traefik_dynamic.toml:/traefik_dynamic.toml
    - /var/:/var/acme.json
    networks:
    - web

networks:
  web: