[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$UStVuPS0$deDjpk9UjNxsU0hczsv2S/"
  ]

[http.routers.api]
  rule = "Host(`monitor.elvinfeng.com`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"

// [http.routers.airflow]
//   rule = "Host(`airflow.elvinfeng.com`)"
//   entrypoints = ["websecure"]
//   middlewares = ["simpleAuth"]
//   service = "webserver"
//   [http.routers.airflow.tls]
//     certResolver = "lets-encrypt"